### ISSUE TITLE
Tests are too slow

### ISSUE THREAD

**Issue by roidelapluie** [theforeman/puppet-puppet#330]
https://travis-ci.org/theforeman/puppet-puppet/builds/90339570

**Comment by domcleal** [comment]
Timeout looks like it's changed from 2 hours to 20 minutes, which I guess is why.

**Comment by domcleal** [comment]
Other jobs are timing out after 10 minutes when no console activity is detected.  I'm not sure why the list of tests hasn't begun here: https://travis-ci.org/theforeman/puppet-puppet/jobs/90386162

**Comment by roidelapluie** [comment]
It is slow on my laptop too. that is very strange and I suspect that facterdb could be the bottleneck.

**Comment by roidelapluie** [comment]
@dominic there are 2 timeouts for travis:

120 minutes for a build.
10 minutes without output.

We are reaching the second one.

**Comment by roidelapluie** [comment]
Opened rspec-puppet-facts#21

**Comment by domcleal** [comment]
jgrep 1.4.0 is released with some big performance improvements.  I'm re-running the tests on master and it's immediately past the bit where it timed out after ten minutes (https://travis-ci.org/theforeman/puppet-puppet/jobs/93178389).

**Comment by domcleal** [comment]
The current state on master (https://travis-ci.org/theforeman/puppet-puppet/builds/93412213) seems to be five regular failures:

1. Ruby 2.0.0 tests for all OSes are being killed after ~50 minutes, probably OOM.  I think rspec/rspec-puppet's still holding catalogs in memory, looking into it further.
2. Ruby 1.9.3 tests for all OSes are *just* reaching 2 hours and timing out.  Curiously not 1.8.7!
3. Puppet 2.7 tests are failing due to an incompatibility in puppetlabs/concat, I posted to foreman-users about dropping support.

**Comment by roidelapluie** [comment]
@domcleal it looks like it is you latest commit: https://github.com/rodjek/rspec-puppet/commit/5c5421045248283a4fb5a6732c3dce600c5637b2

**Comment by domcleal** [comment]
@roidelapluie unfortunately it doesn't fully fix it as we've got an equivalent monkey patch in our spec_helper.rb, but it's not enough.

I filed https://github.com/rodjek/rspec-puppet/pull/333 with a further fix for the OOMs (which even happen on my local system with it consuming upwards of 4GB).  We could put a workaround in our spec_helper for this too, e.g.

<pre>
RSpec.configure do |c|
  c.after(:each) { @catalogue = nil }
end
</pre>

**Comment by domcleal** [comment]
> Ruby 1.9.3 tests for all OSes are just reaching 2 hours and timing out. Curiously not 1.8.7!

I noticed in my build with the latest rspec-puppet memory usage fix (https://travis-ci.org/domcleal/puppet-puppet/builds/93687348) that the 1.9.3 tests are now fast, but the 1.8.7 tests are timing out instead, but I don't know why at the moment.

My best guess is that the fix has helped 1.9.3 in the same way it helped 2.0.0 from OOMing by reducing the size of the MRI, speeding it up.  I don't know why this wouldn't also have helped 1.8.7, and if it has made it worse, why that would be...

The change does slightly change how caching between adjacent examples within a single group works, i.e. `describe { it {}; it {}; it {}; }` will now do more work in rspec-puppet's `load_catalogue` before it hits the catalog cache in `build_catalog`, while before it had a shared catalog instance variable.  It's possible it's this, but I'd have thought the reduced memory usage would offset it.

We could also simply adjust the test matrix to reduce the number of OSes tested on Ruby 1.8.7 since only a few are going to be applicable, in the same way that FreeBSD isn't tested on 1.8.7.

**Comment by roidelapluie** [comment]
@domcleal can you re-trigger a build to see if it is consistent?

**Comment by domcleal** [comment]
> @domcleal can you re-trigger a build to see if it is consistent?

Sure, running https://travis-ci.org/domcleal/puppet-puppet/builds/93901758.

**Comment by roidelapluie** [comment]
I have pushed foreman-installer-modulesync#21 will test it on my fork

**Comment by roidelapluie** [comment]
Tests with theforeman/foreman-installer-modulesync#21 https://travis-ci.org/roidelapluie/puppet-puppet/builds/93905353

**Comment by domcleal** [comment]
> > @domcleal can you re-trigger a build to see if it is consistent?
> 
> Sure, running https://travis-ci.org/domcleal/puppet-puppet/builds/93901758.

Slow again, with a 1.8.7 build at 107 minutes and the other timing out at 120 mins.

It's curious though if you compare it against my test build of the `@catalogue = nil` workaround with the current rspec-puppet release (https://travis-ci.org/domcleal/puppet-puppet/builds/93932305, https://github.com/theforeman/foreman-installer-modulesync/pull/22) which completes 1.8.7 builds in 77 and 90 minutes.  I might test rspec-puppet master in case there's a small performance regression.

**Comment by domcleal** [comment]
(Not that 1.8.7's a big concern, especially after your change to reduce the OSes further.)

**Comment by roidelapluie** [comment]
@domcleal https://travis-ci.org/roidelapluie/puppet-puppet/builds/93906554 was built with your fork of rspec puppet.

I do not plan to try to optimize further 1.8.7, I just hope we can get the last fix for rspec puppet in place.

**Comment by domcleal** [comment]
The workaround for the rspec catalogue variable issue's in modulesync now and I've started syncing it, we'll merge the modulesync branches in as they go green(er).  Last up will be Puppet 2.7 support.

**Comment by roidelapluie** [comment]
Links for the tests: https://travis-ci.org/theforeman/puppet-puppet/builds/94114246

**Comment by domcleal** [comment]
modulesync is merged into master.  The only outstanding issue is Puppet 2.7's show_diff problem.

Thanks for all your work @roidelapluie, I think we've solved the slow tests for the time being!

**Comment by roidelapluie** [comment]
Thanks! Closing this issue as the puppet 2.7 issue is unrelated.
