### ISSUE TITLE
Systemd dependency missing

### ISSUE THREAD

**Issue by amateo** [theforeman/puppet-puppet#704]
I'm trying to install puppetsever with your module, but I get:
```
Error: Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'systemd::dropin_file' (file: /home/amateo_adm/puppetcode/puppet/manifests/server/puppetserver.pp, line: 196, column: 7) on node mus50.um.es
```
I have to manually install module `camptocamp/systemd` to fix it, so I guess it could be listed in requirements.

**Comment by ekohl** [comment]
This is documented at https://github.com/theforeman/puppet-puppet#soft-dependencies

**Comment by walkamongus** [comment]
I just wanted to question this dependency as I feel it potentially reaches too far outside of module scope. Should an application-specific module for puppet require a specific module for managing something as fundamental/system-wide as systemd? I certainly see that it makes things easier but it also means if this module is used, you can't use any other systemd module.

**Comment by jay7x** [comment]
Just curious why puppet::agent::service::systemd is creating systemd unit & timer files directly (not using systemd module) then?

**Comment by ekohl** [comment]
@jay7x that's a good point. The explanation is mostly historical. We added those when the systemd module wasn't as complete as today. It is probably a good idea to rewrite that to use the module as well. That might also be a good reason to make it a hard dependency since then there's functionality in both the agent and the server that uses it.

**Comment by ekohl** [comment]
https://github.com/theforeman/puppet-puppet/pull/710 should fix that.
