### ISSUE TITLE
Support multiple path in environmentpath parameter

### ISSUE THREAD

**Issue by achevalet** [theforeman/puppet-puppet#708]
Currently only one path is accepted. puppet.conf is correctly updated but it fails on folder creation. We probably need a loop at https://github.com/theforeman/puppet-puppet/blob/master/manifests/server/config.pp#L225 

ref: https://puppet.com/docs/puppet/6.4/environments_creating.html#environmentpath

**Comment by ekohl** [comment]
We can split it on `:` but if there's a variable in there (which is valid for Puppet), it will be an issue. Probably good to special case that and make the user responsible for it. Could you come up with a patch for this?

**Comment by achevalet** [comment]
Actually there are other references to `$envs_dir` or `$server_envs_dir`:

```
manifests/params.pp:248:  $server_common_modules_path  = unique(["${server_envs_dir}/common", "${codedir}/modules", "${sharedir}/modules", '/usr/share/puppet/modules'])
manifests/server.pp:463:      $config_version_cmd = "git --git-dir ${envs_dir}/\$environment/.git describe --all --long"
manifests/server/config.pp:253:      require => File[$::puppet::vardir, $::puppet::server::envs_dir],
templates/server/post-receive.erb:13:ENVIRONMENT_BASEDIR = "<%= scope.lookupvar("puppet::server::envs_dir") %>"
```

which makes it not so easy to support multiple values with a single parameter..

**Comment by cabrinha** [comment]
To add on to this, I'm currently having an issue where my servers insist on creating the "common" environment **and restarting puppetserver service**, but my r10k runs remove this environment.

Is there a way to disable the creating of this environment?

**Comment by ekohl** [comment]
You can set `puppet::server_common_modules_path` to an empty string

**Comment by cabrinha** [comment]
> You can set `puppet::server_common_modules_path` to an empty string

Thanks for the quick reply... What would happen if I just set it to:

`/etc/puppetlabs/code/modules`?

**Comment by ekohl** [comment]
That would work as well.

**Comment by optiz0r** [comment]
I find myself wanting this functionality so that I can have r10k manage environments that have been committed to git, but also have some other environments present on the puppetserver which are not managed by r10k. r10k will purge unknown environments, and I don't believe this behaviour is configurable. One workaround is to have the puppetserver use two environmentpath directories, only one of which is managed by r10k, and the other contains the unmanaged environments.

I have implemented support for `envs_dir` to contain multiple colon-separated paths as described in this issue. I've not been able to properly test installing the updated module from git into the foreman puppet modules directory, but by manually applying the patch from this commit over the top of the files foreman-installer puts down on disk, these changes do work at least for the foreman-installer options I'm using. I've added some additional spec tests to validate the multiple envs_dir behaviour, and confirmed that all other related tests still pass. I'm seeing some tests fail relating to cron resources when running the tests locally, but I'm hoping this is just a local environment issue and these will pass when the PR is tested under CI. I will need someone to approve the CI workflow to know if that's the case.

One of the references to `envs_dir` parameter is interpolation into the `config_version_cmd` variable, which is itself used in the `environment.conf.erb` template, however, I cannot spot any references to this template actually being deployed by the current manifests. Is that template obsolete?

**Comment by optiz0r** [comment]
PR for dropping the `config_version` related parameters in #805. PR #803 is dependent on #805, and has been updated to use the string or array, rather than colon-separated string.

I'm still seeing spec tests fail on cron resources, but I haven't touched anything relating to that, so I'm not sure why that's happening. Looking at previous commits, there seem to be various CI failures, though not relating to cron either.
