### ISSUE TITLE
puppet module is unusable at sites that do not have a compatible ::systemd namespace

### ISSUE THREAD

**Issue by pkranenburg** [theforeman/puppet-puppet#799]
The current ::puppet module calls upon resources defined in the **::systemd** module namespace. Notably, this is the case in ::puppet::server::puppetserver (call to 'systemd::dropin_file') and in ::puppet::agent::service::systemd ('systemd::timer'). In the latter manifest the inclusion of the systemd::timer resource takes place even if the 'systemd timer' method is not enabled.

This construction precludes the use of the theforeman/puppet module at sites that cannot provide the expected '::systemd' interface, e.g. because the namespace is already occupied by an alternative systemd puppet module. This drastically reduces the universal usability for a relatively small gain as far as code complexity is concerned.

The ultimate fix for situations like these would require a feature in puppet that would enable a module to include another module in a private namespace. Referals from within the including module (i.e. in this particular case, the calls to ::systemd resources) would work as expected. However, the namespace would not be visible from modules other than the one including it.

Until such a private namespace puppet feature is available, published modules should take care not to trample on namespaces outside their own module.

**Comment by ekohl** [comment]
> This drastically reduces the universal usability for a relatively small gain as far as code complexity is concerned.

I disagree with that, in particular the systemd timer and other [ordering/workarounds](https://github.com/voxpupuli/puppet-systemd/blob/65af359246f2ae2dae277797a0133f49ba7979aa/manifests/unit_file.pp#L98-L114) are good examples where there's more code complexity than you'd think.

> The ultimate fix for situations like these would require a feature in puppet that would enable a module to include another module in a private namespace. Referals from within the including module (i.e. in this particular case, the calls to ::systemd resources) would work as expected. However, the namespace would not be visible from modules other than the one including it.
>
> Until such a private namespace puppet feature is available, published modules should take care not to trample on namespaces outside their own module.

While I agree that Puppet never solved namespacing quite right (other issues are around moving from one to another), I don't see how the current situation tramples on namespaces outside their own module. We have a dependency declared in our `metadata.json` and utilize it.

> In the latter manifest the inclusion of the systemd::timer resource takes place even if the 'systemd timer' method is not enabled.

The reason for that is a user can switch between runmodes. That's why it is there: to ensure it's absent. You can override `unavailable_runmodes` to disable it. It would still leave the service overrides on the server side though which can be a problem.

**Comment by ekohl** [comment]
At this point I think the Vox Pupuli systemd module is very common. Even puppetlabs/postgresql has started to depend on it.
