### ISSUE TITLE
updating puppetserver 6.x -> 7.x fails without manual intervention

### ISSUE THREAD

**Issue by jhoblitt** [theforeman/puppet-puppet#846]
It appears that something akin to the `puppetlabs/transition` mod may be needed in order to allow the puppserver process to be temporarily stopped to run the puppet7 ca migration:

```bash
Notice: /Stage[main]/Puppet::Server::Config/Exec[migrate Puppetserver cadir]/returns: Puppetserver service is running. Please stop it before attempting to run this command.
Error: '/opt/puppetlabs/bin/puppetserver ca migrate' returned 1 instead of one of [0]
Error: /Stage[main]/Puppet::Server::Config/Exec[migrate Puppetserver cadir]/returns: change from 'notrun' to ['0'] failed: '/opt/puppetlabs/bin/puppetserver ca migrate' returned 1 instead of one of [0] (corrective)
Notice: /Stage[main]/Puppet::Server::Config/Exec[puppet_server_config-generate_ca_cert]: Dependency Exec[migrate Puppetserver cadir] has failures: true
Warning: /Stage[main]/Puppet::Server::Config/Exec[puppet_server_config-generate_ca_cert]: Skipping because of failed dependencies
```
The fix is to manually stop puppetserver and run the ca migration:

```bash
[root@foreman ~]# systemctl stop puppetserver
[root@foreman ~]# /opt/puppetlabs/bin/puppetserver ca migrate
CA dir successfully migrated to /etc/puppetlabs/puppetserver/ca. Symlink placed at /etc/puppetlabs/puppet/ssl/ca
for backwards compatibility. The puppetserver can be safely restarted now.
[root@foreman ~]# systemctl start puppetserver
```

**Comment by ekohl** [comment]
Yes, we worked around this in our installer using [a hook](https://github.com/theforeman/foreman-installer/blob/develop/hooks/pre/31-puppet_server_migrate_ca.rb) combined with code here:
https://github.com/theforeman/puppet-puppet/blob/9421bd4ec9fb819fb40c15789886f7bf55b12fab/manifests/server/config.pp#L168-L179

I was a bit scared to automate too much here. For example, if the puppetserver is down, will the agent continue correctly? In our installer it's safe because it's essentially "just" a serverless Puppet agent run, but in complex environments it often isn't so clear.

I'd love to hear some more suggestions on how to deal with this.

**Comment by jhoblitt** [comment]
I am trying to do the upgrade as part of a regular agent run, not using the foreman-installer, which means puppet is managing puppet.  What I can state for sure is that as-is, this results in puppetserver breaking.  I am not sure if solving that needs to be automated.  I think the only way for this to work is for the puppetserver to be stopped during the agent run with the transition module.  This should be acceptable as puppetserver doesn't generally need to be accessible by the agent after the catalog has been downloaded.  I suppose it might result in the agent report being lost if the puppetserver is still down at the end of the agent run.

**Comment by ekohl** [comment]
In https://github.com/theforeman/puppet-puppet/pull/873 we're dropping Puppet 6 support, including the migration. I don't think we're going to get to this anymore.
